export const APP_LOGGED_IN = 'APP_LOGGED_IN';
export const APP_LOGGED_OUT = 'APP_LOGGED_OUT';
export const APP_MODULE_CHANGE = 'APP_MODULE_CHANGE';
export const APP_LOADING_DONE = 'APP_LOADING_DONE';
export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_SHOW_SIDEBAR = 'APP_SHOW_SIDEBAR';
export const APP_HIDE_SIDEBAR = 'APP_HIDE_SIDEBAR';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_LOCATIONS_LOADING_START = 'FETCH_LOCATIONS_LOADING_START';
export const FETCH_LOCATIONS_FULFILLED = 'FETCH_LOCATIONS_FULFILLED';
export const FETCH_LOCATIONS_FAILED = 'FETCH_LOCATIONS_FAILED';
export const FETCH_LOCATIONS_CANCELED = 'FETCH_LOCATIONS_CANCELED';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const SEARCH_LOCATION_FULFILLED = 'SEARCH_LOCATION_FULFILLED';

