export const ADDRESS_SEARCH = 'ADDRESS SEARCH';
export const ADDRESS_SEARCH_LOADING_START = 'ADDRESS_SEARCH_LOADING_START';
export const ADDRESS_SEARCH_FULFILLED = 'ADDRESS_SEARCH_FULFILLED';
export const ADDRESS_SEARCH_FULFILLED_WITH_NO_MATCH = 'ADDRESS_SEARCH_FULFILLED_WITH_NO_MATCH';
export const ADDRESS_SEARCH_CLEAR_SUGGESTIONS = 'ADDRESS_SEARCH_CLEAR_SUGGESTIONS';